In [5]:
import numpy as np
import pandas as pd

array_numpy = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

array_numpy

df = pd.DataFrame(array_numpy, columns=['a', 'b', 'c', 'd', 'e'])

df

a  b  c  d   e
0  1  2  3  4   5
1  6  7  8  9  10

In [6]:
linha = array_numpy[0, :]
linha

array([1, 2, 3, 4, 5])

In [9]:
soma_linhas = array_numpy.sum(axis=0)
soma_linhas

array([ 7,  9, 11, 13, 15])

In [ ]:
[1, 2, 3, 4, 5 ]
[6, 7, 8, 9, 10]


In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [14]:
data_list = ["banana", 2, 3, 4, 5, 6]
serie = pd.Series(data_list)

serie

0    banana
1         2
2         3
3         4
4         5
5         6
dtype: object

In [15]:
data_dict = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}
serie_1 = pd.Series(data_dict)

serie_1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [17]:
serie[2]
serie_1["b"]

2

In [21]:
data = np.array([1,2,np.nan,4,5, np.nan])

limpar_data = data[~np.isnan(data)]

limpar_data

array([1., 2., 4., 5.])

In [23]:
data_duplicatas = np.array([1, 2, 2, 3, 4, 4, 5])

valor_unicos = np.unique(data_duplicatas)

valor_unicos

array([1, 2, 3, 4, 5])

In [25]:
result = np.mean(valor_unicos)
result

3.0

In [27]:
result_2 = np.mean(data_duplicatas) - 1

result_2

2.0

In [28]:
data = {
    "A": [1, 2, np.nan, 4, 5],
    "B": [6, 7, 8, 9, 10],
    "C": [11, 12, np.nan, 14, 15]
}

df = pd.DataFrame(data)

df

A   B     C
0  1.0   6  11.0
1  2.0   7  12.0
2  NaN   8   NaN
3  4.0   9  14.0
4  5.0  10  15.0

In [30]:
df_dropped = df.dropna()
df_dropped

A   B     C
0  1.0   6  11.0
1  2.0   7  12.0
3  4.0   9  14.0
4  5.0  10  15.0

In [32]:
df_dropped_1 = df.dropna(axis=1)
df_dropped_1

B
0   6
1   7
2   8
3   9
4  10